channels:
  - conda-forge
dependencies:
  - python=3.8
  - altair
  - cairo
  - cairosvg
  - jedi=0.17.2
  - jupyterlab
  - line_profiler
  - keras
  - matplotlib
  - numpy
  - noise
  - pandas
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - py5
    - autokeras
